openapi: 3.0.0
info:
  description: API doc
  title: Save the qween
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: This url is used for testing api's locally
paths:
  /signup:
    post:
      description: game creation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                role:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: account created successfully
        '400':
          description: A JSON array of response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    format: bool
                    example: true
                  message:
                    type: string
                    example: Error message
  /login:
    post:
      description: game creation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    example: false
                  token: 
                    type: string
                    
                  data:
                   type: object
                   properties:
                     id:
                      type: string
                     name:
                      type: string
                     role:
                      type: string
                      
        '400':
          description: A JSON array of response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    format: bool
                    example: true
                  message:
                    type: string
                    example: Error message
  /game:
    post:
      description: game creation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                admin_id:
                  type: string
                client:
                  type: string
                contact_person:
                  type: string
                partner:
                  type: string
                date:
                  type: string
                time_zone:
                  type: string
                time:
                  type: string
                teams:
                  type: string
                total_hints:
                  type: string    
                hint_time_penalty:
                  type: string
                game_duration:
                  type: string                      
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: game created successfully
        '400':
          description: A JSON array of response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    format: bool
                    example: true
                  message:
                    type: string
                    example: Error message
      security:
        - Auth: []  
    get:
      description: Responds with the list of games
      responses:
        '200':
          description: A JSON array of response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    format: bool
                    example: false
                  totalcount:
                    type: number
                    example: 0
                  data:
                      type: object
                      properties:
                        admin_id:
                          type: string
                        client:
                          type: string
                        contact_person:
                          type: string
                        partner:
                          type: string
                        date:
                          type: string
                        time_zone:
                          type: string
                        time:
                          type: string
                        teams:
                          type: string
                        total_hints:
                          type: string    
                        hint_time_penalty:
                          type: string
                        game_duration:
                          type: string       
        '400':
          description: A JSON array of response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    format: bool
                    example: true
                  message:
                    type: string
                    example: Error message
      security:
        - Auth: []                      
components:
  securitySchemes:
    Auth:            
      type: http
      scheme: bearer
      bearerFormat: JWT                     
